language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mvila@3base.com
  api_key:
    secure: c+uZ9YBvidegm33t5YExqVGPT2j/KobLO6/Pjf0qCwQpm1HF64pfbuCvUN8SGOLKSh+hr02P8XvGOtE2aVW9eYEuoPJa+Q+ayw9jOpXzl06hVKgWgI+zYvAwonEWs4bqocrcR6FAba4qaHSyWBwaQyvJzn6oPNCrUN7epCRO2RTpEFwTsSerugZtM6Q0OkXnfh/gFrlVGK1y6z4GMtaCOwC6TfHkflRuKyDtwjP5PRnPTYKrP5cjLzJYFDFdVBQez6s+8JepjCguhb5aCbdHSB5JVJpVpmlfBo1D+sVoo+cKLzPW8IVNIC10wo8oKp9G1PqiXWU1CXXyahteiikImtn11G0RLbI2oeUFIHLJTAK2fuUBqlMZP9Cjq/qin/nRslStRGAeGOsaN7ZFf+cWifHGIrmLr8Ln8ytVugUJUVQJllGS4WMgOwAiv/uDvZqhNFl4Ulhn+SPjJNlz0j84OQeBr4Q1Im0MAno+HFW1zydwtv3CPSnX7d/h94CHHcol7cDdufwzyJxdepzTgl8AZPloF6s3ymsSv2d3D45h2tGBGGCrAPD7QdO2DfNIQrrmBgxqvOa5YE5ffsV7R+Mr6UqLhSHr/d3BKI4UGJoeMogRhkJvIljiKugaB0ZRr79xppDuLwv4D+D+ICF4jBJ3ArTrJ2gEmRw+T7GF7CBtOYo=
  skip_cleanup: true
notifications:
  email: false
  slack:
    secure: WDA6/QrxWmoATtozjPLEntST1nT4rcXZUjbbXO66mYqXHKTDbBVzRFBQJYE0TaOZh7CA7pPd41stGwr2LtbKbGnpjWdUbtkgUI0gYZa6QpHxvlnXgZkbbqc+4E/4uOXfihS3DDwvJsWNDxEXTRNJ8P/ahx67/scuvBO+7qoEanqGrESLnZcvkO4o33sJUjnVnBQp3BnB8fmjuzyVqkqFEQcUF4N4hf3A3tcll0+Eu+BJtP6gi3JaYE9qKvXMe8DTLipZw/5ZcKOmmcNk9oDKD37KCp9gyLyETUl5cIIuBjk7av/G35LicLgiPy7qbuGVIJv9LjdwW3iI13wLR9wcjb4mdQaFMfA6ti/+1/qK6oNK1MK2lIDNUS9WMSW8vOLP8YV9zPcEbYE8fEli4+SX3MJ0s4dqpo2Lj7ckUDC9c1G0eRd29RAVVk4s0/KZeS1/GiGbp7A5UeSGbVHkhHc0Tz37jec6nHsOAAUY87qUTcYdWyfqPyH627Ipvq6fte95FU3x4VV2pgzSlSrnlv1y6Y7QoLky2WjsRsVBXxYiincT9XOyNRZXceF62jqr6z0jvFXYotxZtcvk0ovjoVSYbekYIQvjumtHZ0vbSS4scJacedSTM548O9veWdsm1HMMyhX+vNRRrMmmWbVHA7TiyATyIJHA9cfjd+SVFA84k/4=
sudo: false
